### ISSUE TITLE
Error about spring.datasource.url

### ISSUE THREAD

**Issue by rberlind** [hashicorp-demoapp/payments#9]
I'm getting an error with the payments-api app while using it in Nomad: `Could not resolve placeholder 'spring.datasource.url' in value "${spring.datasource.url}"` with the 0.0.11 version when trying to use the transform engine with the posgresql option.  

I also see an INFO message on the first line of the log saying "Vault location [secret/application] not resolvable: Not found", but I suspect that is a red herring and not causing the error.

I have the following files customized:

local/bootstrap.yml:
```
spring:
  cloud:
    vault:
      enabled: true
      fail-fast: true
      authentication: TOKEN
      token: <a_vault_token>
      host: server-a-1
      port: 8200
      scheme: http
```

(By the way, would the case of "TOKEN" matter; originally, the team that created this demo. used "token", but they reported it working.  I switched to "TOKEN" because that is what I see in the docs and example files in this repo.)

local/application.properties:
```
app.storage=db
app.encryption.enabled=true
app.encryption.path=transform
app.encryption.key=payments
```

I do not have a custmized application.yml.

I suspect the problem could be that application.properties is not being found.

The task also has these environment variables set:
```
env {
        SPRING_CONFIG_LOCATION = "file:/local/"
        SPRING_CLOUD_BOOTSTRAP_LOCATION = "file:/local/"
}
```

Here is the full task group definition:
```
  # Payment API component handles payments
  group "payments-api" {
    count = 1

    network {
      port "http_port" {
        static = 8080
      }
      dns {
        servers = ["172.17.0.1"]
      }
    }

    restart {
      attempts = 10
      interval = "5m"
      delay    = "25s"
      mode     = "delay"
    }

  # Define update strategy for the Payments API
    update {
      canary  = 1
    }

    # Service definition to be sent to Consul with corresponding health check
    service {
      name = "payments-api-server"
      port = "http_port"
      tags = ["payments-api"]
      check {
        type     = "tcp"
        interval = "10s"
        timeout  = "2s"
      }
    }

    task "payments-api" {
      driver = "java"

      # Creation of the template file defining how the API will access the database
      template {
        destination   = "local/application.properties"
        data = <<EOF
app.storage=db
app.encryption.enabled=true
app.encryption.path=transform
app.encryption.key=payments
EOF
      }

      # Creation of the template file defining how to connect to vault
      template {
        destination   = "local/bootstrap.yml"
        data = <<EOF
spring:
  cloud:
    vault:
      enabled: true
      fail-fast: true
      authentication: TOKEN
      token: REPLACETOKEN
      host: server-a-1
      port: 8200
      scheme: http
EOF
      }

      # Task relevant environment variables necessary
      env {
        SPRING_CONFIG_LOCATION = "file:/local/"
        SPRING_CLOUD_BOOTSTRAP_LOCATION = "file:/local/"
      }

      # Product-api Docker image location and configuration

     config {
        jar_path    = "local/spring-boot-payments-0.0.11.jar"
        jvm_options = ["-Xmx1024m", "-Xms256m"]
      }

      artifact {
         source = "https://github.com/hashicorp-demoapp/payments/releases/download/v0.0.11/spring-boot-payments-0.0.11.jar"
      }

      # Host machine resources required
      resources {
        cpu    = 300
        memory = 512
      }

      scaling "cpu" {
        policy {
          cooldown            = "1m"
          evaluation_interval = "1m"
          check "95pct" {
            strategy "app-sizing-percentile" {
              percentile = "95"
            }
          }
        }
      } # End scaling cpu

      scaling "mem" {
        policy {
          cooldown            = "1m"
          evaluation_interval = "1m"
          check "max" {
            strategy "app-sizing-max" {}
          }
        }
      } # End scaling mem

    } # end payments-api task
  } # end payments-api group
```

Any ideas? Thanks.

**Comment by rberlind** [comment]
I also want to note that I just tested 0.0.5 and that everything worked with the same nomad job spec (other than the change of version).

**Comment by rberlind** [comment]
I wonder if the problem is caused by changes in application.yml.  The version from 0.0.5 does not have spring.application.name whereas the current version of https://github.com/hashicorp-demoapp/payments/blob/main/src/main/resources/application.yaml shows that. Also, the current version has spring.h2.console.settings.web-allow-others, although I would not think that would matter.

That being said, I have no idea why the addition of spring.application.name would cause problems to the app when used in Nomad.

Perhaps there is an extra environment variable that needs to be set for the app in Nomad?

**Comment by rberlind** [comment]
With help from @lanceplarsen , I was able to verify that adding these four lines to bootstrap.yml got rid of the INFO message, `Vault location [secret/application] not resolvable: Not found`:

```
kv:
   enabled: false
generic:
   enabled: false
```

**Comment by rberlind** [comment]
We might want to add a note about using those in the README.md

**Comment by lanceplarsen** [comment]
Closing this as it was a property file loading issue. Removed the below and it works

```
      env {
        SPRING_CONFIG_LOCATION = "file:/local/"
        SPRING_CLOUD_BOOTSTRAP_LOCATION = "file:/local/"
      }
```
